/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agnelli.eslasfida_pag73;

/**
 *
 * @author philippe
 */
public class MainSfida extends javax.swing.JFrame {

    /**
     * Creates new form MainSfida
     */
    public MainSfida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cassaInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        puntataInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        vincitaInput = new javax.swing.JTextField();
        giocaBottone = new javax.swing.JButton();
        numeroUno = new javax.swing.JTextField();
        numeroTre = new javax.swing.JTextField();
        numeroQuattro = new javax.swing.JTextField();
        numeroDue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cassa:");

        cassaInput.setText("0");

        jLabel2.setText("Puntata:");

        jLabel3.setText("Vincita:");

        vincitaInput.setText("0");
        vincitaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vincitaInputActionPerformed(evt);
            }
        });

        giocaBottone.setText("Gioca");
        giocaBottone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giocaBottoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(giocaBottone, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cassaInput, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(puntataInput)
                        .addComponent(vincitaInput))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numeroUno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroDue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroTre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroQuattro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cassaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(puntataInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vincitaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giocaBottone, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroTre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroQuattro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setField(int uno, int due, int tre, int quattro) {
        numeroUno.setText(String.valueOf(uno));
        numeroDue.setText(String.valueOf(due));
        numeroTre.setText(String.valueOf(tre));
        numeroQuattro.setText(String.valueOf(quattro));
    }
    
    private int compareNumeri(int numero_1, int numero_2, int numero_3) {
        int num = 0;
        
        if(numero_1 == numero_2) num++;
        if(numero_1 == numero_3) num++;
        
        return num;
    }
    
    private int getNumeriUguali(int uno, int due, int tre, int quattro) {
        int num = 1;
        
        if(uno == due) {
            num += 1 + compareNumeri(uno, tre, quattro);
                  
        }else if(uno == tre){
            num += 1 + compareNumeri(uno, quattro, -1);
        }
        else if(uno == quattro){
            num++;
        }
        
        else if(due == tre) {
            num += 1 + compareNumeri(uno, quattro, -1);
        }
        
        else if(due == quattro) {
            num++;
        }
        
        else if(tre == quattro) {
            num++;
        }
        
        return num;
    }
    
   
    
    private void giocaBottoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giocaBottoneActionPerformed
        Integer puntata = new Integer(puntataInput.getText());
        Integer cassa = new Integer(cassaInput.getText());
        Integer vincita = new Integer(vincitaInput.getText());
        int uno = 1 + ((int)Math.random()* 10);
        int due = 1 +((int)Math.random()* 10);
        int tre = 1 +((int)Math.random()* 10);
        int quattro = 1 +((int)Math.random()* 10);
        setField(uno, due, tre, quattro);
        int num = getNumeriUguali(uno, due, tre, quattro);
        if(num > 1) vincita = puntata * num;
        vincitaInput.setText(vincita.toString());
        cassa += vincita;
        cassaInput.setText(cassa.toString());
       
    }//GEN-LAST:event_giocaBottoneActionPerformed

    private void vincitaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vincitaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vincitaInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSfida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSfida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSfida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSfida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSfida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cassaInput;
    private javax.swing.JButton giocaBottone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField numeroDue;
    private javax.swing.JTextField numeroQuattro;
    private javax.swing.JTextField numeroTre;
    private javax.swing.JTextField numeroUno;
    private javax.swing.JTextField puntataInput;
    private javax.swing.JTextField vincitaInput;
    // End of variables declaration//GEN-END:variables
}
